format = """
$directory\
$character"""

right_format = """
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$vcsh\
$fossil_branch\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$env_var\
$crystal\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$os\
$container\
$shell"""

[character]
success_symbol = "[](green)"
error_symbol = "[](red)"
vimcmd_symbol = "[](green)"
vimcmd_replace_one_symbol = "[](purple)"
vimcmd_replace_symbol = "[](purple)"
vimcmd_visual_symbol = "[](yellow)"

[line_break]
disabled = true

[aws]

symbol = "\ue33d  "



[buf]

symbol = "\uf49d "



[c]

symbol = "\ue61e "



[conda]

symbol = "\uf10c "



[dart]

symbol = "\ue798 "



[directory]

read_only = " \uf83d"



[docker_context]

symbol = "\uf308 "



[elixir]

symbol = "\ue275 "



[elm]

symbol = "\ue62c "



[git_branch]

symbol = "\uf418 "



[golang]

symbol = "\ue627 "



[haskell]

symbol = "\ue777 "



[hg_branch]

symbol = "\uf418 "



[java]

symbol = "\ue256 "



[julia]

symbol = "\ue624 "



[memory_usage]

symbol = "\uf85a "



[nim]

symbol = "\uf6a4 "



[nix_shell]

symbol = "\uf2dc "



[nodejs]

symbol = "\ue718 "



[package]

symbol = "\uf8d6 "



[python]

symbol = "\ue235 "



[spack]

symbol = "\U0001f162 "



[rust]

symbol = "\ue7a8 "


